# Generated by Django 5.2.7 on 2025-11-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reset_otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
