# Generated by Django 5.2.9 on 2025-12-06 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('not_completed', 'Not Completed'), ('patient_Demographics', 'Patient Demographics'), ('medical_history', 'Medical History'), ('surgery_Factors', 'Surgery Factors'), ('preoperative_considerations', 'Preoperative Considerations'), ('postoperative', 'Post Operative'), ('planned_Anesthesia', 'Planned Anesthesia')], default='not_completed', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_scores', to='surveys.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=255)),
                ('selected_option', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.survey')),
            ],
        ),
    ]
