# Generated by Django 5.2.6 on 2025-09-24 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_score', models.IntegerField(default=0)),
                ('medical_score', models.IntegerField(default=0)),
                ('preop_score', models.IntegerField(default=0)),
                ('surgery_score', models.IntegerField(default=0)),
                ('anesthetic_score', models.IntegerField(default=0)),
                ('postop_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('selected_option', models.TextField(blank=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.survey')),
            ],
        ),
    ]
