# Generated by Django 5.2.7 on 2025-10-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='section_name',
        ),
    ]
