# Generated by Django 5.2.6 on 2025-09-24 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='anesthetic_score',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='medical_score',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='patient_score',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='postop_score',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='preop_score',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='surgery_score',
        ),
        migrations.AddField(
            model_name='survey',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.survey')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
            ],
            options={
                'unique_together': {('survey', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.survey')),
            ],
            options={
                'unique_together': {('survey', 'name')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.section'),
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
    ]
