# Generated by Django 5.2.7 on 2025-10-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('not_completed', 'Not Completed'), ('patient_Demographics', 'Patient Demographics'), ('medical_history', 'Medical History'), ('surgery_Factors', 'Surgery Factors'), ('preoperative_considerations', 'Preoperative Considerations'), ('postoperative', 'Post Operative'), ('planned_Anesthesia', 'Planned Anesthesia')], default='not_completed', max_length=100),
        ),
    ]
